import { usePlatform } from '@/api/hooks'
import { useAlerts } from '@/api/hooks/useAlerts'
import { Badge, Card, Grid, PlatformPage, Stats, platformStyles as styles } from '@/components/platform-dashboard'
import { usePersistentState } from '@/core/persistence'

type Event={id:string;time:string;ip:string;method:string;path:string;score:number;severity:string;detection_type:string;status:string;response_action:string;rules:string[]}
type Data={events:number;high_confidence:number;average_score:number;rule_hits:{name:string;count:number}[];top_sources:{ip:string;count:number}[];timeline:Event[]}
export function Component(){const {data,isLoading}=usePlatform<Data>('detection','/platform/detection');const {alerts,isConnected}=useAlerts();const [show,setShow]=usePersistentState('tab-history-detection.showAll',true);if(isLoading||!data)return <div className={styles.page}></div>;const events=(data.timeline||[]).slice().reverse();return <PlatformPage title="Real-Time Attack Detection" subtitle="Timestamped detections from the live ingestion, rules and ML pipeline" right={<span className={styles.live}>{isConnected?'● SOCKET CONNECTED':'○ SOCKET OFFLINE'}</span>}><Stats items={[{label:'Detected events',value:data.events,meta:'Stored telemetry'},{label:'High confidence',value:data.high_confidence,meta:'Score ≥ 0.80'},{label:'Avg score',value:data.average_score.toFixed(2),meta:'Threat score'},{label:'Live alerts',value:alerts.length,meta:'Current browser stream'}]}/><Grid><Card title="Top detection rules">{data.rule_hits.length?data.rule_hits.map(x=><div className={styles.barRow} key={x.name}><span>{x.name}</span><div className={styles.bar}><div className={styles.fill} style={{width:`${Math.min(100,x.count/Math.max(1,...data.rule_hits.map(r=>r.count))*100)}%`}}/></div><b>{x.count}</b></div>):<div className={styles.muted}>No stored rule hits.</div>}</Card><Card title="Top source IPs"><table className={styles.table}><thead><tr><th>IP</th><th>Events</th></tr></thead><tbody>{data.top_sources.map(x=><tr key={x.ip}><td>{x.ip}</td><td>{x.count}</td></tr>)}</tbody></table></Card></Grid><Card title="Detection timeline"><div className={styles.row} style={{justifyContent:'space-between',marginBottom:8}}><span className={styles.muted}>Each row is a real stored event; newest events appear first.</span><label style={{display:'flex',gap:6}}><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/> Show all details</label></div><table className={styles.table}><thead><tr><th>Timestamp</th><th>Source</th><th>Request</th><th>Detection</th><th>Score</th><th>Severity</th><th>Status</th><th>Action</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{new Date(e.time).toLocaleString()}</td><td>{e.ip}</td><td>{e.method} {e.path}</td><td>{e.detection_type}{show&&e.rules.length?<><br/><small>{e.rules.join(', ')}</small></>:null}</td><td>{e.score.toFixed(2)}</td><td><Badge value={e.severity}/></td><td>{e.status}</td><td>{e.response_action}</td></tr>)}</tbody></table>{!events.length&&<div className={styles.empty}>Waiting for telemetry…</div>}</Card></PlatformPage>}
Component.displayName='DetectionDashboard'
