import { useEffect, useState } from 'react'
import { apiClient } from '@/core/api'
import s from '../shared.module.scss'
export function Component():React.ReactElement{const [logged,setLogged]=useState(!!sessionStorage.getItem('cybersentinel_token'));const [u,setU]=useState('admin');const [p,setP]=useState('Admin@123');const [team,setTeam]=useState<any[]>([]);const [role,setRole]=useState('viewer');const [nu,setNu]=useState('');const [np,setNp]=useState('');const [nd,setNd]=useState('');
 async function login(){try{const r=await apiClient.post('/auth/login',{username:u,password:p});sessionStorage.setItem('cybersentinel_token',r.data.token);setLogged(true);load()}catch(e:any){alert(e?.response?.data?.detail||'Login failed')}} async function load(){try{setTeam((await apiClient.get('/auth/team')).data)}catch{}} useEffect(()=>{if(logged)load()},[])
 async function create(){try{await apiClient.post('/auth/team',{username:nu,password:np,display_name:nd,role});setNu('');setNp('');setNd('');load()}catch(e:any){alert(e?.response?.data?.detail||'Admin login required')}}
 if(!logged)return <div className={s.page}><div className={`${s.card} ${s.auth}`}><h2 className={s.title}>CyberSentinel Team Login</h2><p className={s.sub}>Demo credentials are pre-seeded for the final-year project. Change them through your deployment environment for real use.</p><label className={s.label}>Username<input className={s.input} value={u} onChange={e=>setU(e.target.value)}/></label><label className={s.label}>Password<input className={s.input} type="password" value={p} onChange={e=>setP(e.target.value)}/></label><button className={s.button} onClick={login}>Sign in</button><div className={s.notice} style={{marginTop:12}}>Demo: admin / Admin@123 · analyst / Analyst@123 · viewer / Viewer@123</div></div></div>
 return <div className={s.page}><div className={s.hero}><div><h2 className={s.title}>Authentication & Team</h2><p className={s.sub}>RBAC roles: admin, analyst and viewer.</p></div><button className={`${s.button} ${s.secondary}`} onClick={()=>{sessionStorage.removeItem('cybersentinel_token');setLogged(false)}}>Sign out</button></div><div className={s.grid}><section className={s.card}><h3>Team members</h3><table className={s.table}><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Permissions</th></tr></thead><tbody>{team.map(x=><tr key={x.id}><td><strong>{x.display_name}</strong><br/>{x.username}</td><td>{x.role}</td><td>{x.active?'Active':'Disabled'}</td><td>{x.permissions.join(', ')}</td></tr>)}</tbody></table></section><section className={s.card}><h3>Add member (admin)</h3><label className={s.label}>Username<input className={s.input} value={nu} onChange={e=>setNu(e.target.value)}/></label><label className={s.label}>Display name<input className={s.input} value={nd} onChange={e=>setNd(e.target.value)}/></label><label className={s.label}>Password<input className={s.input} value={np} onChange={e=>setNp(e.target.value)}/></label><label className={s.label}>Role<select className={s.select} value={role} onChange={e=>setRole(e.target.value)}><option>viewer</option><option>analyst</option><option>admin</option></select></label><button className={s.button} onClick={create}>Create member</button></section></div></div>}
Component.displayName='Team'
