import { useState } from 'react'
import { apiClient } from '@/core/api'
import s from '../shared.module.scss'
export function Component():React.ReactElement{const [target,setTarget]=useState('example.com');const [items,setItems]=useState<any[]>([]);const [busy,setBusy]=useState(false);const [filter,setFilter]=useState('ALL')
 async function scan(){setBusy(true);try{const r=await apiClient.post('/security/vulnerability-scan',{target});setItems(r.data.findings||[])}catch(e:any){alert(e?.response?.data?.detail||'Assessment failed. Check that the backend is running and the target is reachable.')}finally{setBusy(false)}}
 async function update(id:string,status:string){await apiClient.patch(`/security/vulnerabilities/${id}`,{status});setItems(v=>v.map(x=>x.id===id?{...x,status}:x))}
 const shown=items.filter(x=>filter==='ALL'||x.severity===filter||x.status===filter)
 return <div className={s.page}><div className={s.hero}><div><h2 className={s.title}>Vulnerability Assessment</h2><p className={s.sub}>Find missing headers, weak transport controls, exposed files, directory listing and insecure cookies.</p></div></div><div className={s.card}><div className={s.row}><input className={s.input} value={target} onChange={e=>setTarget(e.target.value)} /><button className={s.button} onClick={scan} disabled={busy}>{busy?'Scanning…':'Run assessment'}</button><select className={s.select} style={{width:160}} value={filter} onChange={e=>setFilter(e.target.value)}><option>ALL</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option><option>OPEN</option><option>RESOLVED</option><option>ACCEPTED</option></select></div></div><div className={s.grid3}>{shown.map(x=><article className={s.finding} key={x.id}><div className={s.row}><span className={`${s.badge} ${s[x.severity as keyof typeof s]}`}>{x.severity}</span><span className={`${s.badge} ${s[x.status as keyof typeof s]}`}>{x.status}</span></div><h4>{x.name}</h4><p>{x.description}</p><p><strong>Affected:</strong> {x.affected_asset}</p><p><strong>Evidence:</strong> {x.evidence}</p><p><strong>Fix:</strong> {x.recommended_fix}</p><div className={s.row}><button className={s.button} onClick={()=>update(x.id,'RESOLVED')}>Resolve</button><button className={`${s.button} ${s.secondary}`} onClick={()=>update(x.id,'ACCEPTED')}>Accept</button></div></article>)}</div>{!shown.length&&<div className={s.card}><div className={s.empty}>No findings yet. Run an authorized assessment.</div></div>}</div>}
Component.displayName='VulnerabilityAssessment'
