# CyberSentinel controlled lab reverse proxy.
events { worker_connections 64; }
http {
    log_format vigil '$simulated_ip - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';
    map $http_x_simulated_source_ip $simulated_ip { default $remote_addr; "" $remote_addr; }
    access_log /var/log/nginx/access.log vigil;
    error_log /var/log/nginx/error.log warn;
    upstream target_app { server devlog-app:8000; }
    server {
        listen 80;
        server_name _;
        location / {
            proxy_pass http://target_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $simulated_ip;
            proxy_set_header X-Forwarded-For $simulated_ip;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
